### ISSUE TITLE
Django 1.9 incompatibilities

### ISSUE THREAD

**Issue by debnet** [ekonstantinidis/django-rest-framework-docs#34]
```
"C:\Program Files (x86)\PyCharm\bin\runnerw.exe" D:\VirtualEnvs\nouvelleoffre\Scripts\python.exe D:/Git/nouvelleoffre-back/manage.py runserver 8000
Traceback (most recent call last):
  File "D:/Git/nouvelleoffre-back/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "D:\VirtualEnvs\nouvelleoffre\lib\site-packages\django\core\management\__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "D:\VirtualEnvs\nouvelleoffre\lib\site-packages\django\core\management\__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\VirtualEnvs\nouvelleoffre\lib\site-packages\django\core\management\__init__.py", line 177, in fetch_command
    commands = get_commands()
  File "C:\Python34\lib\functools.py", line 448, in wrapper
    result = user_function(*args, **kwds)
  File "D:\VirtualEnvs\nouvelleoffre\lib\site-packages\django\core\management\__init__.py", line 72, in get_commands
    for app_config in reversed(list(apps.get_app_configs())):
  File "D:\VirtualEnvs\nouvelleoffre\lib\site-packages\django\apps\registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "D:\VirtualEnvs\nouvelleoffre\lib\site-packages\django\apps\registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

Everything works fine when removing "rest_framework_docs" from INSTALLED_APPS.

Thanks.

**Comment by ekonstantinidis** [comment]
Hi @debnet! I did not have the chance to use Django 1.9 extensively yet so I missed that. I'm looking into this one already. Hope to have news soon!

**Comment by ekonstantinidis** [comment]
So I created a fresh Django 1.9 project and installed `drfdocs` but I didn't get any errors. Can you give some more information so I can reproduce this one @debnet ? Thank you!

**Comment by debnet** [comment]
Hi @ekonstantinidis! It seems to be an incompatibility with `django-configurations`, I wrote an issue about it. Thank you for your quick answer.

https://github.com/jazzband/django-configurations/issues/133

**Comment by ekonstantinidis** [comment]
Yes it looks like many packages have this issue with Django 1.9 ([example](https://github.com/etianen/django-reversion/issues/454)) - I guess `drfdocs` works great with Django `1.9` :smile:
